# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#  platform :ios, '8.0'
  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'ObjectMapper', '~> 2.2'
  
  pod 'SVProgressHUD'

pod 'SDWebImage', '~>3.8'

  # Pods for CCSwiftDemo

end
